### ISSUE TITLE
weird sorting

### ISSUE THREAD

**Issue by lmittmann** [pwambach/ethereum-visualization#2]
Hi @pwambach, thanks for the really cool visualization tool.

I'm not sure if this is a bug or a feature, but I noticed when sorting by any criterion the blocks are ordered from top to button and from **right to left**, which feels a little weird.

**Comment by pwambach** [comment]
Hey, thanks!

yeah right, I didn't think about the order to much and just used `flex-wrap: wrap-reverse`.  It probably makes more sense to put the "heavier" black transactions at the bottom of each block and start to fill the blocks from the left side.

Thanks for the comment!

**Comment by pwambach** [comment]
Changed the sort order
