### ISSUE TITLE
Small blocks are centered

### ISSUE THREAD

**Issue by devgar** [pwambach/ethereum-visualization#3]
Blocks so small that they do not fill a row are presented centered because they doesn't meet the css rule ` max-width: 250px;` I suppose replacing it to `width:250px` should fix it.

![captura de pantalla 2018-02-05 a las 11 11 51](https://user-images.githubusercontent.com/2792291/35799413-e4199c3e-0a65-11e8-926e-0815bb9622eb.png)

With a screen width less than 500px does not occur.

**Comment by pwambach** [comment]
Hey, thanks! Good catch! Will change it with the next update...
